### ISSUE TITLE
noclip crashes the programm and doesnt work

### ISSUE THREAD

**Issue by GoldenCheats** [GiFXED/Roblox-FFlag-Editor#2]

**Comment by Teemsploit** [comment]
Sorry about that, a fix will be uploaded in the next 10 mins.

**Comment by Teemsploit** [comment]
Should be fixed, please try the 3.5.1 hotfix, please reply if the issue persists. 

https://github.com/GiFXED/Roblox-FFlag-Editor/releases/tag/HotfixThreePointFivePointOne

**Comment by Teemsploit** [comment]
Seems to be fixed closed.
